version: "3.7"
services:
### MONGO DB ==>
  mongo:
    container_name: Mongo-DB
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongodb:/data/db
    restart: always

#===>END
##
### MONGO UI ===>
  mongo_express:
    container_name: Mongo-UI
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

      ME_CONFIG_BASICAUTH: "false"
      #ME_CONFIG_BASICAUTH_USERNAME: admin
      #ME_CONFIG_BASICAUTH_PASSWORD: sasa1234

      ME_CONFIG_SITE_BASEURL: /ui/mongo
    restart: always

#===>END
##
### NODE_RED ==>
  node_red:
    build: ./data/node-red/
    container_name: Node-RED
    #environment:
    #  - http_proxy=http://188.190.37.193:21280
    ports:
      - "1880:1880"
    volumes:
      - ./data/node-red/data:/data
    restart: always

#===>END
##
### wallet_service ==>
  wallet_service:
    build: ./ms/wallet_service
    container_name: wallet_service
    volumes:
      - ./ms/wallet_service:/app/
      - /app/node_modules/
    ports:
      - 21222:21222
    restart: always
    environment:
      - PORT=21222
      - CONNECT_URL=mongodb://root:example@mongo:27017/wallet?authMechanism=DEFAULT&authSource=admin
    command: npm run dev
#===>END
##
### categories_service ==>
  categories_service:
    build: ./ms/categories_service
    container_name: categories_service
    volumes:
      - ./ms/categories_service:/app/
      - /app/node_modules/
    ports:
      - 21223:21223
    restart: always
    environment:
      - PORT=21223
      - CONNECT_URL=mongodb://root:example@mongo:27017/categories?authMechanism=DEFAULT&authSource=admin
    command: npm run dev

#===>END
##
### UI_service ==>
  ui_service:
    build: ./ms/UI_service
    container_name: ui_service
    volumes:
      - ./ms/UI_service:/app/
      - /app/node_modules/
    ports:
      - 4000:4000
    restart: always
    environment:
      - WALLET_URL=http://wallet_service:21222
      - CATEGORIES_URL=http://categories_service:21223
    command: npm run dev

#===>END
##
### BALANCER ==>
  mariadb:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'nginx_proxy'
      MYSQL_DATABASE: 'nginx_proxy'
      MYSQL_USER: 'nginx_proxy'
      MYSQL_PASSWORD: 'nginx_proxy'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./volume/mysql:/var/lib/mysql

#===>END
##
###  ==> 
  nginx-proxy: 
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "nginx_proxy"
      DB_MYSQL_PASSWORD: "nginx_proxy"
      DB_MYSQL_NAME: "nginx_proxy"
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    volumes:
      - ./data/nginx-proxy/data:/data
      - ./data/nginx-proxy/letsencrypt:/etc/letsencrypt
    #  - nginx-proxy-manager_letsencrypt:/etc/letsencrypt
    restart: always

#===>END
##
###
